metadata:
  displayName: S3Uploader
  builtin: false
  icon: >
    <svg xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16"
    class="yc-icon ServiceIcon" fill="currentColor" stroke="none"
    aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16
    16">

    <path d="M15 5a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2h14zM14 1a1 1 0 0 0-1-1H3a1 1
    0 0 0-1 1v2h12zM15 8H1a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V9a1 1
    0 0 0-1-1zm-5 5H6a1 1 0 0 1 0-2h4a1 1 0 0 1 0 2z"></path>

    </svg></svg>
  description: |
    Tool for uploading data to the S3
  helpUrl: null
  version: v0.0.1
  example: ''
  labels:
    - pipe
    - Deploy
  public: true
  organization: null
  name: S3Uploader
  developer: gitee-team
  latest: true
dynamicRender: true
environments: null
kind: Kubernetes
companyUuid: itone
version: v1.0.0
cacheDefault: null
spec:
  image: giteeru/s3uploader:v0.0.1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  endpoint: |
    /usr/bin/artifactsextractor -debug && \
     /usr/bin/s3ycdiruploader -uploaddir "${UPLOAD_DIR}" -bucket "${AWS_BUCKET}" -akid "${AWS_ACCESS_KEY_ID}" -asak "${AWS_SECRET_ACCESS_KEY}"
result: null
arguments:
  - hidden: false
    defaultValue: ''
    description: Directory, where data will be uploaded.
    rules: ^.{1,64}$
    label: Uploading Directory
    remote: null
    type: input
    toolbar:
      addButton: false
    showCondition: null
    children: null
    hint: null
    dateSource: null
    name: UPLOAD_DIR
    alias: UPLOAD_DIR
    must: true
    style:
      width: '1'
    table:
      showHeader: true
      showSerialNumber: true
  - hidden: false
    defaultValue: ''
    description: Name of the bucket, that will be used.
    rules: ^.{1,64}$
    label: S3 bucket name
    remote: null
    type: input
    toolbar:
      addButton: false
    showCondition: null
    children: null
    hint: null
    dateSource: null
    name: AWS_BUCKET
    alias: AWS_BUCKET
    must: true
    style:
      width: '1'
    table:
      showHeader: true
      showSerialNumber: true
  - hidden: false
    defaultValue: ''
    description: ID of the access key, that was recieved while bucket creation.
    rules: ^.{1,64}$
    label: AWS access key ID
    remote: null
    type: password
    toolbar:
      addButton: false
    showCondition: null
    children: null
    hint: null
    dateSource: null
    name: AWS_ACCESS_KEY_ID
    alias: AWS_ACCESS_KEY_ID
    must: true
    style:
      width: '1'
    table:
      showHeader: true
      showSerialNumber: true
  - hidden: false
    defaultValue: ''
    description: Access key, that was recieved while bucket creation.
    rules: ^.{1,64}$
    label: AWS secret key
    remote: null
    type: password
    toolbar:
      addButton: false
    showCondition: null
    children: null
    hint: null
    dateSource: null
    name: AWS_SECRET_ACCESS_KEY
    alias: AWS_SECRET_ACCESS_KEY
    must: true
    style:
      width: '1'
    table:
      showHeader: true
      showSerialNumber: true
cacheSwitch: false
